title: Yusuf Shaidu

<p align="justify">
  <img src="https://raw.githubusercontent.com/yusufshaidu/yusufshaidu.github.io/main/likedin_picture.jpeg" align="right" width="200" style="border-radius: 50%;" alt="Yusuf Shaidu">

Postdoctoral Researcher at the University of California, Berkeley, & <br /> 
Lawrence Berkeley National Laboratory (LBL). <br />
Contact: yshaidu@berkeley.edu
</p>
description: Research in DFT, MLIPs and Materials Modeling
theme: minima
