title: Yusuf Shaidu
description: Computational Materials Scientist | MLIPs | DFT | MOFs

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme

# Required for GitHub Pages
minimal_mistakes_skin: default

# Fix build issues
locale: "en-US"
markdown: kramdown
